heapster:
  image:
    repository: reg.lifesense.com/google_containers/heapster
    tag: v1.5.3 
  resizer:
    image:
      repository: reg.lifesense.com/google_containers/addon-resizer
      tag: 1.8.1

gcpreviews:
  image:
    repository: reg.lifesense.com/jenkinsxio/builder-go

controllerbuild:
  image:
    repository: reg.lifesense.com/jenkinsxio/builder-go

controllerteam:
  image:
    repository: reg.lifesense.com/jenkinsxio/builder-go

docker-registry:
  enabled: true
  persistence:
    size: 100Gi

nexus:
  enabled: true
  image:
    repository: reg.lifesense.com/jenkinsxio/nexus
    tag: 0.1.6
nexusServiceLink:
  enabled: false
  externalName: ""

chartmuseum:
  enabled: true
  persistence:
    enabled: true
    AccessMode: ReadWriteOnce
    Size: 8Gi
  env:
    open:
      AUTH_ANONYMOUS_GET: true
      DISABLE_API: false
    secret:
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: admin
  image:
    tag: v0.7.1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 160m
      memory: 128Mi
chartmuseumServiceLink:
  enabled: false

  # specify the external name here for where the chartmuseum should be
  externalName: ""

monocular:
  enabled: true

jenkins:
  enabled: true
  Master:
    Image: "jenkinsxio/jenkinsx"
    ImageTag: "0.0.46"
    AdminUser: admin
    AdminPassword: admin

  Servers:
    BitbucketCloud:
    #- Name: myname
    #  Url: https://something.com/
    #  Credential: some-cred-name

    BitbucketServer:
    #- Name: myname
    #  Url: https://something.com/
    #  Credential: some-cred-name

    GHE:
    #- Name: myname
    #  Url: https://something.com/
    #  Credential: some-cred-name

    Gitea:
    #- Name: myname
    #  Url: https://something.com/
    #  Credential: some-cred-name

    GitLab:
    #- Name: myname
    #  Url: https://something.com/
    #  Credential: some-cred-name

    # global node properties
    Global:
      EnvVars:
        DOCKER_REGISTRY: ""
        TILLER_NAMESPACE: ""

  Agent:
    Enabled: true
    PodTemplates:
      aws-cdk:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          aws-cdk:
            Image: reg.lifesense.com/jenkinsxio/builder-maven-nodejs:0.1.324
      Maven:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Maven:
            Image: reg.lifesense.com/jenkinsxio/builder-maven:0.1.324
      Maven-Java11:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Maven:
            Image: reg.lifesense.com/jenkinsxio/builder-maven-java11:0.1.324
      Gradle:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Gradle:
            Image: reg.lifesense.com/jenkinsxio/builder-gradle:0.1.324
      Scala:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Scala:
            Image: reg.lifesense.com/jenkinsxio/builder-scala:0.1.324
      Go:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Go:
            Image: reg.lifesense.com/jenkinsxio/builder-go:0.1.324
      Terraform:
        Containers:
          Jnlp:
          Terraform:
            Image: reg.lifesense.com/jenkinsxio/builder-terraform:0.1.324
      Rust:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Rust:
            Image: reg.lifesense.com/jenkinsxio/builder-rust:0.1.324
      Newman:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Newman:
            Image: reg.lifesense.com/jenkinsxio/builder-newman:0.1.324
      Nodejs:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Nodejs:
            Image: reg.lifesense.com/jenkinsxio/builder-nodejs:0.1.324
      Maven-Nodejs:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          MavenNodejs:
            Image: reg.lifesense.com/jenkinsxio/builder-maven-nodejs:0.1.324
      JX-base:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          JX-base:
            Image: reg.lifesense.com/jenkinsxio/builder-jx:0.1.324
      Promote:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Promote:
            Image: reg.lifesense.com/jenkinsxio/builder-jx:0.1.324
      Python2:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Python:
            Image: reg.lifesense.com/jenkinsxio/builder-python2:0.1.324
      Python:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Python:
            Image: reg.lifesense.com/jenkinsxio/builder-python:0.1.324
      Python37:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Python:
            Image: reg.lifesense.com/jenkinsxio/builder-python37:0.1.324
      Ruby:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Ruby:
            Image: reg.lifesense.com/jenkinsxio/builder-ruby:0.1.324
      Swift:
        Name: swift
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Swift:
            Image: reg.lifesense.com/jenkinsxio/builder-swift:0.1.324
      Dlang:
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
          Dlang:
            Image: reg.lifesense.com/jenkinsxio/builder-dlang:0.1.324
  Persistence:
    Enabled: true
    AccessMode: ReadWriteOnce
    Size: 30Gi

grafana:
  server:
    adminUser: "admin"
    adminPassword: "admin"